/* ============================================================================
   findings.js — canonical findings catalog for L0 + L1 prototypes
   ============================================================================
   Single source of truth. Both drafts/l0.html and drafts/l1_v17.html import
   from here so the two prototypes can never drift on IDs, severities, or copy.

   Source: memory/findings.md v3 (2026-04-29) with CS7 hard-removal applied
   per DECISIONS_LOG #65 (2026-04-30 — verified-fixed during audit window).
   54 findings across 5 themes. CS7 retired. T9 retired.

   Schema:
     {
       id: 'CC2',                         // canonical theme-prefixed ID
       theme: 'CC',                       // CC | CS | AQ | AD | FG
       severity: 'p0',                    // p0 | p1 | p2
       originalId: 'G3',                  // legacy ID for traceability
       phase: 1,                          // 1 | 1.5 | 2 | 3 | 5
       fieldTypes: ['longText','dropdown'],
       title: '…',                        // full title
       oneliner: '…',                     // one-sentence hook
       problem: '…',                      // full body
       fix: '…',                          // 1-sentence fix
       variantsAffected: '…',
       linkedFindings: ['CC5','CS12'],
       umbrella: 'CC1',                   // optional — parent finding ID
       evidenceTemplate: 'A',             // A–F per design-system spec
       evidenceHeadline: '… / … / …',     // 3-line headline
       userLens: ['New user','Power user'],
       goalAlignment: ['Adoption','CSAT'],
       anchors: [                         // multi-screen per D-Rev-8
         { screen: 'settings-longText', el: 'field-name', anchor: 'top-right', offsetX: -6, offsetY: 6 },
         …
       ],
     }
============================================================================ */

/* -------------------- Themes -------------------- */
const THEMES = {
  CC: {
    name: 'Coordination',
    fullName: 'Controls Coordinate',
    color: '#6647F0',  // ClickUp purple
    dotColor: '#6647F0',
    description: "The Settings Screen form fails to coordinate — controls don't talk to each other; defaults bind to path rather than to template.",
  },
  CS: {
    name: 'Consistency',
    fullName: 'Consistency across variants',
    color: '#0091FF',  // project blue
    dotColor: '#0091FF',
    description: 'Three-variant divergence (View / Task / CFM) on the Settings Screen and Type Selection picker.',
  },
  AQ: {
    name: 'Quality',
    fullName: 'AI Quality + Transparency',
    color: '#FF02F0',  // ClickUp pink
    dotColor: '#FF02F0',
    description: 'Prompt UX, AI output quality, billing/cost transparency, automation disclosure.',
  },
  AD: {
    name: 'Discovery',
    fullName: 'AI Discovery + Adoption',
    color: '#FC6D2D',  // orange
    dotColor: '#FC6D2D',
    description: 'New user onboarding journey, brand consistency, where AI shows up (or doesn\'t).',
  },
  FG: {
    name: 'Gaps',
    fullName: 'Feature Gaps',
    color: '#22C55E',  // green
    dotColor: '#22C55E',
    description: "Net-new capabilities the product doesn't have today — preview, prompt library, output types.",
  },
};

/* -------------------- Severity -------------------- */
const SEVERITY = {
  p0: { label: 'P0', color: '#DC2626', dotColor: '#DC2626' },        // red
  p1: { label: 'P1', color: '#F97316', dotColor: '#F97316' },        // orange
  p2: { label: 'P2', color: '#EAB308', dotColor: '#EAB308' },        // yellow
};

/* -------------------- Screens -------------------- */
// Used by L0 to map anchors[].screen → which canvas the pin renders on.
const SCREENS = {
  'settings-longText':       { label: 'Settings · Long Text',          section: 2 },
  'settings-dropdown':       { label: 'Settings · Dropdown',           section: 3 },
  'typeSelection':           { label: 'Type Selection picker',         section: 1 },
  'cfm':                     { label: 'Custom Field Manager',          section: 4 },
  'wizardStep5':             { label: 'Wizard Step 5',                 section: 5 },
  'workspaceLanding':        { label: 'Workspace landing',             section: 5 },
  'sidebarNav':              { label: 'Sidebar nav',                   section: 5 },
  'brainHub':                { label: 'Brain hub',                     section: 5 },
  'plannerPage':             { label: 'Planner',                       section: 5 },
  'getStartedList':          { label: 'Get Started list',              section: 5 },
  'getStartedAITask':        { label: 'Get Started AI task',           section: 5 },
  'getStartedWorkflowTask':  { label: 'Get Started workflow task',     section: 5 },
  'helpDocs':                { label: 'Help docs',                     section: 5 },
  'globalSearch':            { label: 'Global search',                 section: 5 },
};

/* -------------------- Onboarding carousel stages (10 frames) -------------------- */
// Locked 2026-04-30: 10 frames, full journey (Q1).
const ONBOARDING_STAGES = [
  { id: 'wizardStep5',            label: 'Wizard Step 5' },
  { id: 'workspaceLanding',       label: 'Workspace landing' },
  { id: 'sidebarNav',             label: 'Sidebar' },
  { id: 'brainHub',               label: 'Brain hub' },
  { id: 'plannerPage',            label: 'Planner' },
  { id: 'getStartedList',         label: 'Get Started list' },
  { id: 'getStartedAITask',       label: 'Get Started AI task' },
  { id: 'getStartedWorkflowTask', label: 'Get Started workflow task' },
  { id: 'helpDocs',               label: 'Help docs' },
  { id: 'globalSearch',           label: 'Global search' },
];

/* -------------------- Umbrella narratives (L1 only) -------------------- */
// Three umbrella cards on L1 Chapter 1. Not pinned on L0 canvases.
const UMBRELLAS = [
  {
    id: 'A1',
    catalogRef: 'Theme CC · Controls Coordinate',
    title: "Controls don't coordinate with each other",
    oneliner: "Each control acts alone. Template changes don't update Field name. Format locks. Translation's Property picker gets stuck.",
    finding: "Header picker updates dependent fields correctly; Template dropdown doesn't. Three different \"stuck\" moments in one sitting, no error messaging.",
    suggestion: "Bind every control to one form model. Template change cascades to Field name, Format, Property, Language — each resets to the template's default.",
    rollup: ['CC2', 'CC3', 'CC4', 'CC5'],
  },
  {
    id: 'A2',
    catalogRef: 'Theme CS · Path-driven divergence',
    title: "Form doesn't coordinate with the path the user took",
    oneliner: 'Same entry point, same template, different form depending on path.',
    finding: 'manual→fillwithAI shows the Fill method switcher and defaults Progress Updates to "Today." AI-direct hides the switcher and defaults to "Last 24 hours." Different AI output from what should be the same configuration.',
    suggestion: 'Path shouldn\'t determine form state. Fill method renders everywhere. Progress Updates defaults to "Last 24 hours" on every path.',
    rollup: ['CS14', 'CS16'],
  },
  {
    id: 'A3',
    catalogRef: 'Theme CS · Cross-entry-point divergence',
    title: 'Same form looks different depending on where you opened it',
    oneliner: 'Three entry points, three layouts, three capability sets. CFM — the admin flow — has fewer controls than View.',
    finding: 'View gets full permissions. Task has no Settings section at all. CFM shows Pinned + Visible-to-Guests only. Same form, three execution paths.',
    suggestion: 'One component, three contexts. Variants differ in width and density, not controls. Full Settings + Permissions renders everywhere.',
    rollup: ['CS15', 'CS2', 'CS4'],
  },
];

/* -------------------- Findings (54) -------------------- */
const FINDINGS = [
  /* ============================================================
     CC — Controls Coordinate (5)
  ============================================================ */
  {
    id: 'CC1', theme: 'CC', severity: 'p0', originalId: 'G1', phase: 1,
    fieldTypes: ['longText', 'dropdown'],
    title: "The form's controls don't talk to each other",
    oneliner: 'The Settings Screen looks like one form, but it doesn\'t coordinate. Controls don\'t talk to each other.',
    problem: "The Settings Screen looks like one form, but it doesn't coordinate. Controls don't talk to each other, and the form silently behaves differently depending on the path the user took to get here.",
    fix: 'Treat the Settings Screen as one coordinated form; bind defaults to template, not to path.',
    variantsAffected: 'All entry points · all AI templates · both paths · both field types',
    linkedFindings: ['CC2', 'CS14', 'CS15', 'AQ6', 'AQ7', 'CC3', 'CS16', 'CC4', 'CC5'],
    evidenceTemplate: 'D',
    evidenceHeadline: "The form's controls / don't talk / to each other.",
    userLens: ['New user', 'Power user'],
    goalAlignment: ['Adoption', 'CSAT'],
    anchors: [
      { screen: 'settings-longText', el: '__panel__' },
      { screen: 'settings-dropdown', el: '__panel__' },
    ],
  },
  {
    id: 'CC2', theme: 'CC', severity: 'p0', originalId: 'G3', phase: 1,
    fieldTypes: ['longText', 'dropdown'],
    title: 'Field name doesn\'t update when the Template changes',
    oneliner: 'Switch Template from Summary to Action Items → Field name still says "Summary."',
    problem: "When the user changes the Template dropdown (long text: Summary → Action Items; dropdown: Sentiment → T-shirt Size), the Field name stays at whatever it was before. The Header type picker handles this correctly; the Template dropdown doesn't.",
    fix: 'Re-derive the field name from the active template whenever the template selector changes.',
    variantsAffected: 'Categorize · T-shirt Size · Sentiment · Custom · Summary · Progress Updates · Translation · Action Items',
    linkedFindings: ['CC5', 'CS12'],
    umbrella: 'CC1',
    evidenceTemplate: 'A',
    evidenceHeadline: "Field name / doesn't update when / Template changes.",
    userLens: ['New user', 'Power user'],
    goalAlignment: ['Adoption', 'CSAT'],
    behavioral: true,
    anchors: [
      { screen: 'settings-longText', el: 'field-name', anchor: 'top-right', offsetX: -6, offsetY: 6 },
      { screen: 'settings-dropdown', el: 'field-name', anchor: 'top-right', offsetX: -6, offsetY: 6 },
    ],
  },
  {
    id: 'CC3', theme: 'CC', severity: 'p0', originalId: 'L1', phase: 1,
    fieldTypes: ['longText'],
    title: 'The Format control locks up after two template switches',
    oneliner: 'On Summary or Progress Updates, Format stops responding after the second template switch. No error.',
    problem: 'In the Summary and Progress Updates templates, the Format dropdown (Bulleted list / Short / Traditional) stops responding after a specific sequence: change Format a few times, then switch Template, change Format once more, then switch Template again — Format is now locked. The control still renders and accepts clicks, but selections don\'t apply.',
    fix: 'Keep the Format dropdown responsive across template changes; reset to template default but stay clickable.',
    variantsAffected: 'Summary · Progress Updates templates · all three entry points',
    linkedFindings: [],
    umbrella: 'CC1',
    evidenceTemplate: 'F',
    evidenceHeadline: 'The Format control / locks up after / two template switches.',
    userLens: ['Power user'],
    goalAlignment: ['CSAT'],
    behavioral: true,
    anchors: [
      { screen: 'settings-longText', el: 'template', anchor: 'top-right', offsetX: -6, offsetY: 6 },
    ],
  },
  {
    id: 'CC4', theme: 'CC', severity: 'p1', originalId: 'L3', phase: 1,
    fieldTypes: ['longText'],
    title: "The Translation template's Property picker gets stuck",
    oneliner: 'Pick a custom field as the source once, and the picker stops accepting new selections.',
    problem: 'In the Translation template, the Property picker lets the user choose what to translate (Task Description, Task Name, or a custom field). Once a custom field is picked, the picker appears to accept new clicks but selections don\'t stick. The only way to switch is to first switch back to Task Description or Task Name, then pick the new custom field.',
    fix: 'Keep the Property picker responsive across all source-field selections.',
    variantsAffected: 'Translation template only',
    linkedFindings: [],
    umbrella: 'CC1',
    evidenceTemplate: 'A',
    evidenceHeadline: 'Translation Property / picker gets stuck / on custom fields.',
    userLens: ['New user', 'Power user'],
    goalAlignment: ['Adoption', 'CSAT'],
    behavioral: true,
    anchors: [
      { screen: 'settings-longText', el: 'template', anchor: 'bottom-left', offsetX: 6, offsetY: -14 },
    ],
  },
  {
    id: 'CC5', theme: 'CC', severity: 'p0', originalId: 'D1', phase: 1,
    fieldTypes: ['dropdown'],
    title: 'Template change strands the dropdown options list, breaking AI output',
    oneliner: 'Switch Sentiment → T-shirt Size and the options list stays stuck on Positive/Neutral/Negative. AI picks from the wrong set.',
    problem: 'On dropdown, when the Template changes, the Dropdown options list also gets stranded with the previous template\'s options. The AI prompt updates but the options it picks from don\'t — producing nonsense output (e.g., AI asked to do sentiment analysis with options "XS / S / M / L / XL").',
    fix: 'When the dropdown template changes, refresh the options list to match — preserve user edits with a warning.',
    variantsAffected: 'All AI templates on dropdown · all three entry points',
    linkedFindings: ['CC2'],
    umbrella: 'CC1',
    evidenceTemplate: 'B',
    evidenceHeadline: 'Template switch / strands the dropdown / options list.',
    userLens: ['New user', 'Power user'],
    goalAlignment: ['Adoption', 'CSAT'],
    behavioral: true,
    anchors: [
      { screen: 'settings-dropdown', el: 'dropdown-options', anchor: 'top-right', offsetX: -6, offsetY: 6 },
    ],
  },

  /* ============================================================
     CS — Consistency across variants (15 — CS7 retired)
  ============================================================ */
  {
    id: 'CS1', theme: 'CS', severity: 'p0', originalId: 'G2', phase: 1,
    fieldTypes: ['longText', 'dropdown'],
    title: 'Three entry points to custom field creation flow (from View / Task / CFM) evolved as three different screen variants',
    oneliner: 'Same screen appears in three variants depending on where the user starts. Each variant evolved independently without a unifying contract.',
    problem: 'The same screen — Custom Field Type Selection and Settings Screen — appears in three variants depending on where the user starts (View / Task / CFM). They share the same underlying component but diverge systematically on copy, behavior, feature exposure, and AI context. Each variant evolved independently without a unifying contract.',
    fix: 'Treat the three variants as one shared component with narrow, documented exceptions. View is the baseline.',
    variantsAffected: 'View · Task · CFM · all paths · all field types',
    linkedFindings: ['CS6', 'CS8', 'CS10'],
    evidenceTemplate: 'C',
    evidenceHeadline: 'Three entries, / three different / screen variants.',
    userLens: ['New user', 'Power user'],
    goalAlignment: ['Adoption', 'CSAT'],
    anchors: [
      { screen: 'settings-longText', el: '__panel__' },
      { screen: 'settings-dropdown', el: '__panel__' },
      { screen: 'typeSelection', el: '__panel__' },
      { screen: 'cfm', el: '__panel__' },
    ],
  },
  {
    id: 'CS2', theme: 'CS', severity: 'p1', originalId: 'G10', phase: 1,
    fieldTypes: ['longText', 'dropdown'],
    title: 'Description field placement inconsistent across variants',
    oneliner: 'View buries Description in More Settings. Task and CFM put it on top with different helper copy.',
    problem: 'The Description field appears in different positions on the form depending on the entry point. Sometimes it\'s between Field name and Type, sometimes below Type, sometimes at the bottom of the form.',
    fix: 'Standardize Description placement across all three variants.',
    variantsAffected: 'View · Task · CFM',
    linkedFindings: [],
    umbrella: 'A3',
    evidenceTemplate: 'C',
    evidenceHeadline: 'Description field / placement inconsistent / across variants.',
    userLens: ['Power user'],
    goalAlignment: ['CSAT'],
    anchors: [
      { screen: 'settings-longText', el: 'more', anchor: 'top-right', offsetX: -6, offsetY: 36 },
      { screen: 'settings-dropdown', el: 'more', anchor: 'top-right', offsetX: -6, offsetY: 36 },
    ],
  },
  {
    id: 'CS3', theme: 'CS', severity: 'p1', originalId: 'G13', phase: 1,
    fieldTypes: ['longText', 'dropdown'],
    title: 'The prompt textarea is a different size across variants',
    oneliner: 'Task: 3 lines. View: 4–5. CFM: 5–6, wider. Most important control on the form is three different sizes.',
    problem: 'The prompt textarea where users write or edit the AI prompt is a different size in each entry point. View has the most generous textarea; Task is cramped; CFM is somewhere in between.',
    fix: 'Standardize the prompt textarea size; use View\'s larger textarea as the baseline.',
    variantsAffected: 'View · Task · CFM',
    linkedFindings: [],
    umbrella: 'A3',
    evidenceTemplate: 'C',
    evidenceHeadline: 'Prompt textarea / different size in / each variant.',
    userLens: ['Power user'],
    goalAlignment: ['CSAT'],
    anchors: [
      { screen: 'settings-longText', el: 'prompt', anchor: 'top-right', offsetX: -6, offsetY: 82 },
      { screen: 'settings-dropdown', el: 'prompt', anchor: 'top-right', offsetX: -6, offsetY: 82 },
    ],
  },
  {
    id: 'CS4', theme: 'CS', severity: 'p2', originalId: 'G14-cluster + T4 + T8', phase: 1,
    fieldTypes: ['longText', 'dropdown'],
    title: 'Settings Screen layout micro-inconsistencies — eight controls treated differently across variants',
    oneliner: 'Eight cross-variant micro-inconsistencies bundled into one cluster: casing, toggles, badges, separators, copy, and icon style.',
    problem: "Eight separate cross-variant micro-inconsistencies bundled into one cluster: (1) 'Visible to Guests' casing/copy varies; (2) 'Pinned' toggle three different treatments; (3) Automations badge inconsistent; (4) Header treatment differs; (5) Section separator treatment differs; (6) '(optional)' modifier inconsistent; (7) action-label copy varies across entry points ('Add a column' / 'Add or create fields' / 'Add field from Workspace' / 'Add existing'); (8) `+` icon style inconsistent (circle on View vs plain on Task).",
    fix: 'Run a Settings Screen + Type Selection consistency pass; adopt View\'s treatment as the baseline.',
    variantsAffected: 'View · Task · CFM · all entry points',
    linkedFindings: [],
    umbrella: 'A3',
    evidenceTemplate: 'C',
    evidenceHeadline: 'Eight controls, / treated differently / across variants.',
    userLens: ['Power user'],
    goalAlignment: ['CSAT'],
    anchors: [
      { screen: 'settings-longText', el: 'more', anchor: 'top-left', offsetX: 6, offsetY: 4 },
      { screen: 'settings-dropdown', el: 'more', anchor: 'top-left', offsetX: 6, offsetY: 4 },
      { screen: 'typeSelection', el: 'header', anchor: 'top-right', offsetX: -6, offsetY: 10 },     // T4 — copy inconsistency
      { screen: 'typeSelection', el: 'header', anchor: 'top-left',  offsetX: 10, offsetY: 94 },    // T8 — + icon inconsistency
    ],
  },
  {
    id: 'CS5', theme: 'CS', severity: 'p2', originalId: 'G19', phase: 1,
    fieldTypes: ['longText', 'dropdown'],
    title: 'CFM uses a two-column layout; Task and View are single-column',
    oneliner: 'CFM uses a two-column layout for the Settings Screen; View and Task use single-column. Two layout systems, same form.',
    problem: 'CFM uses a two-column layout for the Settings Screen; View and Task use single-column. Two layout systems, same form.',
    fix: 'Align CFM to single-column OR document the management-context exception.',
    variantsAffected: 'CFM (compared to View and Task)',
    linkedFindings: [],
    umbrella: 'A3',
    evidenceTemplate: 'B',
    evidenceHeadline: 'CFM uses / two columns; / others single.',
    userLens: ['Power user'],
    goalAlignment: ['CSAT'],
    anchors: [
      { screen: 'cfm', el: '__panel__' },
    ],
  },
  {
    id: 'CS6', theme: 'CS', severity: 'p0', originalId: 'T1', phase: 1,
    fieldTypes: ['longText', 'dropdown'],
    title: 'The Task entry is a degraded variant of the View entry',
    oneliner: 'Task is missing capabilities that View has — Suggested section absent, broken Button field, no Create/Add-existing tabs.',
    problem: 'The Task entry is missing capabilities that View has — Suggested section absent, broken Button field, no Create/Add-existing tabs (pre-step popup instead), worse copy. Users creating fields inside a task get a weaker experience than users creating them from a view.',
    fix: 'Unify the picker across entry points; Task adopts View\'s tabs, Suggested section, and Button handling.',
    variantsAffected: 'All three entry points · Task most affected',
    linkedFindings: ['CS8', 'CS10', 'CS12'],
    umbrella: 'A3',
    evidenceTemplate: 'C',
    evidenceHeadline: 'Task entry / is a degraded variant / of View.',
    userLens: ['New user', 'Power user'],
    goalAlignment: ['Adoption', 'CSAT'],
    anchors: [
      { screen: 'typeSelection', el: 'header', anchor: 'top-left', offsetX: 10, offsetY: 6 },
    ],
  },
  // CS7 — REMOVED 2026-04-30 per DECISIONS_LOG #65 (verified-fixed during audit window).
  {
    id: 'CS8', theme: 'CS', severity: 'p1', originalId: 'T5', phase: 1,
    fieldTypes: ['longText', 'dropdown'],
    title: 'The Suggested section is absent from the Task entry',
    oneliner: 'View has Suggested. Task doesn\'t — even though Task carries richer context.',
    problem: 'When creating a field from inside a task, the Suggested section (Brain-personalized field suggestions) doesn\'t appear. View has it; Task doesn\'t — even though Task carries richer context (task title, description, comments, assignees, etc.) than View does.',
    fix: 'Render the Suggested section in Task entry using View\'s logic + task-level signals.',
    variantsAffected: 'Task only · CFM absence is defensible (no specific task/list context)',
    linkedFindings: ['CS6'],
    umbrella: 'A3',
    evidenceTemplate: 'B',
    evidenceHeadline: 'Suggested section / missing from / Task entry.',
    userLens: ['New user', 'Power user'],
    goalAlignment: ['Adoption', 'CSAT'],
    anchors: [
      { screen: 'typeSelection', el: 'search', anchor: 'top-right', offsetX: -6, offsetY: 38 },
    ],
  },
  {
    id: 'CS9', theme: 'CS', severity: 'p1', originalId: 'T6', phase: 1,
    fieldTypes: ['longText', 'dropdown'],
    title: 'Field Type picker is one flat scroll list with no functional grouping or sort order',
    oneliner: '~33 field types in a single scrollable flat list. Grouped by AI vs standard — internal architecture, not user intent.',
    problem: 'The picker lists ~33 field types in a single scrollable flat list with minimal hierarchy. Fields are grouped by type (AI vs standard) rather than by user intent. A new user trying to add a "priority" field must scan the entire list with no navigational guidance.',
    fix: 'Replace the flat list with six functional groups by user intent.',
    variantsAffected: 'All three entry points',
    linkedFindings: [],
    umbrella: 'A3',
    evidenceTemplate: 'D',
    evidenceHeadline: 'Field Type picker: / flat list, no / functional grouping.',
    userLens: ['New user'],
    goalAlignment: ['Adoption'],
    anchors: [
      { screen: 'typeSelection', el: 'all-fields', anchor: 'top-right', offsetX: -6, offsetY: 6 },
    ],
  },
  {
    id: 'CS10', theme: 'CS', severity: 'p1', originalId: 'T7', phase: 1,
    fieldTypes: ['longText', 'dropdown'],
    title: 'Added pre-step click in Task entry path to select Add Existing vs Create',
    oneliner: 'Task entry shows a popup BEFORE the picker. Pick wrong, back out and restart.',
    problem: 'In the Task entry, clicking + opens a "Create a field" / "Add field from Workspace" popup BEFORE the picker. The user has to pick one or the other before seeing the picker. Once inside, no way to switch — they have to back out and restart. View handles this with in-picker Create new / Add existing tabs.',
    fix: 'Adopt View\'s tabbed pattern in Task; eliminate the pre-step popup.',
    variantsAffected: 'Task only · CFM legitimately doesn\'t need Add-existing',
    linkedFindings: ['CS6'],
    umbrella: 'A3',
    evidenceTemplate: 'B',
    evidenceHeadline: "Task entry adds / a pre-step popup / View doesn't have.",
    userLens: ['New user', 'Power user'],
    goalAlignment: ['Adoption', 'CSAT'],
    anchors: [
      { screen: 'typeSelection', el: 'header', anchor: 'top-left', offsetX: 10, offsetY: 50 },
    ],
  },
  {
    id: 'CS11', theme: 'CS', severity: 'p2', originalId: 'D4', phase: 1,
    fieldTypes: ['dropdown'],
    title: 'Dropdown options appear in different positions across variants',
    oneliner: 'Six paths, six positions for the same control. View AI-direct even puts options BEFORE Template.',
    problem: 'The Dropdown options section appears in a different place in the form depending on entry point and path. View manual-manual: after Field name, before Fill method. View AI-direct: after Field name, before Template. Task: bottom of form. CFM: inside Field Type section. No path shows options in the same place.',
    fix: 'Standardize options position; place after Template, before Automations.',
    variantsAffected: 'All three entry points · both paths · all templates',
    linkedFindings: [],
    umbrella: 'A3',
    evidenceTemplate: 'C',
    evidenceHeadline: 'Dropdown options: / six positions across / six variants.',
    userLens: ['Power user'],
    goalAlignment: ['CSAT'],
    anchors: [
      { screen: 'settings-dropdown', el: 'dropdown-options', anchor: 'bottom-right', offsetX: -6, offsetY: -6 },
    ],
  },
  {
    id: 'CS12', theme: 'CS', severity: 'p1', originalId: 'G11', phase: 1,
    fieldTypes: ['longText', 'dropdown'],
    title: "Field-type names don't match across picker rows, preview cards, and config panels",
    oneliner: 'Same field type, three different names. Each surface uses its own.',
    problem: "Naming inconsistencies across surfaces: 'Custom Text' (picker) vs 'Custom Instructions' (config panel) vs 'Text area (Long Text)' (panel header). 'Money' (picker) vs 'Currency' (preview card). 'Tasks' and 'Relationship' for the same data type. Each field type is named differently in different places.",
    fix: 'Standardize field-type names across picker, preview, and config panel.',
    variantsAffected: 'Long Text · Money · Relationship · Tasks · Custom variants · Categorize · Custom Dropdown',
    linkedFindings: ['AD2'],
    evidenceTemplate: 'C',
    evidenceHeadline: 'Same field type, / three different / names.',
    userLens: ['New user', 'Power user'],
    goalAlignment: ['Adoption', 'CSAT'],
    anchors: [
      { screen: 'settings-longText', el: 'prompt', anchor: 'top-right', offsetX: -6, offsetY: 6 },
      { screen: 'settings-dropdown', el: 'prompt', anchor: 'top-right', offsetX: -6, offsetY: 6 },
      { screen: 'typeSelection', el: 'all-fields', anchor: 'top-right', offsetX: -6, offsetY: 30 },
    ],
  },
  {
    id: 'CS13', theme: 'CS', severity: 'p2', originalId: 'G22', phase: 1,
    fieldTypes: ['longText', 'dropdown'],
    title: "Trigger copy doesn't match the Automations screen",
    oneliner: 'This screen says "when tasks change." The Automations screen says "when task is updated." Same trigger, two phrasings.',
    problem: "Trigger copy in the AI field's Automations section doesn't match the trigger copy shown on the Automations management screen. Same automation, two different descriptions.",
    fix: 'Standardize trigger copy; use the management-screen copy as canonical.',
    variantsAffected: 'All AI templates · Settings Screen · Automations management screen',
    linkedFindings: [],
    evidenceTemplate: 'B',
    evidenceHeadline: 'Same automation, / two different / trigger descriptions.',
    userLens: ['Power user'],
    goalAlignment: ['CSAT'],
    anchors: [
      { screen: 'settings-longText', el: 'autom-trigger', anchor: 'top-right', offsetX: -6, offsetY: 2 },
      { screen: 'settings-dropdown', el: 'autom-trigger', anchor: 'top-right', offsetX: -6, offsetY: 2 },
    ],
  },
  {
    id: 'CS14', theme: 'CS', severity: 'p0', originalId: 'G4', phase: 1,
    fieldTypes: ['longText', 'dropdown'],
    title: 'Fill method toggle is hidden on the AI-direct path, visible on manual→AI',
    oneliner: 'Enter via an AI template and there\'s no way to switch to Manual without cancelling and starting over.',
    problem: 'The Fill method toggle (Manual fill / Fill with AI) is visible on the manual→AI path but hidden on the AI-direct path. Same template, two paths, two different forms — and the user has no way to flip back to Manual without restarting.',
    fix: 'Show the Fill method toggle on every path; bind to template, not path.',
    variantsAffected: 'All AI templates · AI-direct path missing toggle',
    linkedFindings: ['CS15', 'CS16'],
    umbrella: 'A2',
    evidenceTemplate: 'B',
    evidenceHeadline: 'Fill method toggle / hidden on the / AI-direct path.',
    userLens: ['New user', 'Power user'],
    goalAlignment: ['Adoption', 'CSAT'],
    anchors: [
      { screen: 'settings-longText', el: 'template', anchor: 'top-right', offsetX: -6, offsetY: -36 },
      { screen: 'settings-dropdown', el: 'template', anchor: 'top-right', offsetX: -6, offsetY: -36 },
    ],
  },
  {
    id: 'CS15', theme: 'CS', severity: 'p0', originalId: 'G5', phase: 1,
    fieldTypes: ['longText', 'dropdown'],
    title: 'Permissions can only be configured from the View entry point',
    oneliner: 'CFM — the bulk-admin flow — can\'t set permissions on field creation. Neither can Task.',
    problem: 'Permissions settings (who can view/edit the field, guest visibility) are only configurable from the View entry point. Task and CFM hide the permissions section entirely. Permissions are a field-level property but treated as a View-only capability.',
    fix: 'Show Permissions section in all three entry points.',
    variantsAffected: 'Task · CFM (Permissions hidden) · View only (Permissions visible)',
    linkedFindings: [],
    umbrella: 'A3',
    evidenceTemplate: 'C',
    evidenceHeadline: 'Permissions only / from the View / entry point.',
    userLens: ['Admin', 'Power user'],
    goalAlignment: ['CSAT'],
    anchors: [
      { screen: 'settings-longText', el: 'more', anchor: 'top-right', offsetX: -6, offsetY: 4 },
      { screen: 'settings-dropdown', el: 'more', anchor: 'top-right', offsetX: -6, offsetY: 4 },
      { screen: 'cfm', el: '__panel__' },
    ],
  },
  {
    id: 'CS16', theme: 'CS', severity: 'p0', originalId: 'L2', phase: 1,
    fieldTypes: ['longText'],
    title: "Progress Updates default differs by path: 'Today' vs 'Last 24 hours'",
    oneliner: 'manual→fillwithAI defaults to "Today." AI-direct defaults to "Last 24 hours." Same template. Different AI output.',
    problem: "The Progress Updates template's 'Get updates from' default sets the time window the AI summarizes. Default differs by path: manual→AI = 'Today'; AI-direct = 'Last 24 hours'. Same template, same entry point, different defaults. Two users configuring what they think is the same thing get different AI output.",
    fix: 'Pick one default ("Last 24 hours" recommended); use it regardless of path.',
    variantsAffected: 'Progress Updates template only · all entry points · both paths',
    linkedFindings: ['CS14'],
    umbrella: 'A2',
    evidenceTemplate: 'B',
    evidenceHeadline: 'Progress Updates / default differs / by path.',
    userLens: ['New user', 'Power user'],
    goalAlignment: ['Adoption', 'CSAT'],
    behavioral: true,
    anchors: [
      { screen: 'settings-longText', el: 'template', anchor: 'bottom-right', offsetX: -6, offsetY: -6 },
    ],
  },

  /* ============================================================
     AQ — AI Quality + Transparency (12)
  ============================================================ */
  {
    id: 'AQ1', theme: 'AQ', severity: 'p1', originalId: 'G12', phase: 1,
    fieldTypes: ['longText', 'dropdown'],
    title: "The 'Tell AI how to fill out this field' tooltip is redundant",
    oneliner: 'The ⓘ tooltip duplicates the visible label and the prompt textarea\'s placeholder.',
    problem: "The tooltip 'Tell AI how to fill out this field' duplicates the visible label and the prompt textarea's placeholder. Three places say the same thing; users get no additional information from the tooltip.",
    fix: 'Remove the redundant tooltip or replace with content that adds value.',
    variantsAffected: 'All AI templates · all entry points',
    linkedFindings: [],
    evidenceTemplate: 'A',
    evidenceHeadline: 'Tooltip duplicates / the label and / placeholder.',
    userLens: ['New user', 'Power user'],
    goalAlignment: ['CSAT'],
    anchors: [
      { screen: 'settings-longText', el: 'prompt', anchor: 'top-right', offsetX: -6, offsetY: 58 },
      { screen: 'settings-dropdown', el: 'prompt', anchor: 'top-right', offsetX: -6, offsetY: 58 },
    ],
  },
  {
    id: 'AQ2', theme: 'AQ', severity: 'p2', originalId: 'G23', phase: 1,
    fieldTypes: ['longText', 'dropdown'],
    title: 'Default template prompts have copy and structure issues',
    oneliner: 'Seven default prompts ship with AI fields. Voice and structure inconsistencies across all of them.',
    problem: "The 7 default template prompts that ship with AI fields have varied issues: jargon ('most appropriate option'), inconsistent voice (some imperative, some declarative), structural issues (mixing content and format instructions). Users who edit prompts inherit these patterns.",
    fix: 'Run a copy pass on all 7 default prompts; standardize voice and structure.',
    variantsAffected: 'Sentiment · T-shirt Size · Categorize · Custom Dropdown · Summary · Progress Updates · Action Items · Translation',
    linkedFindings: ['AQ10'],
    evidenceTemplate: 'D',
    evidenceHeadline: 'Seven default / prompts, seven / different voices.',
    userLens: ['Power user'],
    goalAlignment: ['CSAT'],
    behavioral: true,
    anchors: [
      { screen: 'settings-longText', el: 'prompt', anchor: 'top-left', offsetX: 6, offsetY: 30 },
      { screen: 'settings-dropdown', el: 'prompt', anchor: 'top-left', offsetX: 6, offsetY: 30 },
    ],
  },
  {
    id: 'AQ3', theme: 'AQ', severity: 'p1', originalId: 'L4', phase: 1,
    fieldTypes: ['longText'],
    title: 'The Format dropdown tooltips are wrong or misleading',
    oneliner: '"Bulleted list" tooltip says "one bullet per task" (wrong). "Traditional" says "tasks grouped by list" (factually wrong).',
    problem: 'Format dropdown has three options (Bulleted list / Short / Traditional) with tooltips that are factually wrong or misleading. "Bulleted list" tooltip says "one bullet per task" (wrong — single-task field has multiple bullets). "Traditional" tooltip describes "tasks grouped by list and status" (factually wrong — outputs a long paragraph). Tooltip copy looks like it was written for a different feature.',
    fix: 'Replace tooltips with accurate copy; rename "Short" and "Traditional" to clearer names.',
    variantsAffected: 'Summary · Progress Updates templates',
    linkedFindings: [],
    evidenceTemplate: 'D',
    evidenceHeadline: 'Format dropdown / tooltips are / factually wrong.',
    userLens: ['New user', 'Power user'],
    goalAlignment: ['CSAT'],
    anchors: [
      { screen: 'settings-longText', el: 'prompt', anchor: 'top-right', offsetX: -6, offsetY: 34 },
    ],
  },
  {
    id: 'AQ4', theme: 'AQ', severity: 'p1', originalId: 'D3', phase: 1,
    fieldTypes: ['dropdown'],
    title: "'Manual' sort label collides with Fill method 'Manual' and doesn't clearly identify as sort method",
    oneliner: 'The ⇅ sort control reads "Manual." The Fill method toggle reads "Manual fill." Same word, two meanings.',
    problem: "The sort-order toggle on Dropdown options shows '[⇅ Manual]'. Two problems: (1) 'Manual' doesn't read as a sort state — users have to infer; (2) 'Manual' collides with the Fill method 'Manual fill' label elsewhere on the form, referring to two unrelated things.",
    fix: 'Rewrite label: "Sort: Custom / A–Z / Z–A."',
    variantsAffected: 'All dropdown variants · all templates · all entry points',
    linkedFindings: [],
    evidenceTemplate: 'A',
    evidenceHeadline: "'Manual' sort / label collides with / Fill method.",
    userLens: ['New user', 'Power user'],
    goalAlignment: ['CSAT'],
    anchors: [
      { screen: 'settings-dropdown', el: 'dropdown-options', anchor: 'top-right', offsetX: -6, offsetY: -12 },
    ],
  },
  {
    id: 'AQ5', theme: 'AQ', severity: 'p1', originalId: 'OB23 reframed', phase: 3,
    fieldTypes: ['longText', 'dropdown'],
    title: 'All four AI ClickApps are ON by default for new accounts — no disclosure of additional charges',
    oneliner: 'Four AI ClickApps default ON. No copy explains they incur additional charges against the workspace plan.',
    problem: 'Settings → Apps → AI & Search shows four ClickApps (AI, AI Notetaker, Automation, Connected Search) — all ON by default for new accounts. No disclosure that these features incur additional charges against the workspace\'s plan allotment.',
    fix: 'Add cost/allotment disclosure on the ClickApps screen.',
    variantsAffected: 'All new accounts · all four AI ClickApps',
    linkedFindings: ['AQ6', 'AQ9'],
    evidenceTemplate: 'A',
    evidenceHeadline: 'AI ClickApps / ON by default, / no cost disclosure.',
    userLens: ['New user', 'Admin'],
    goalAlignment: ['Adoption', 'CSAT'],
    anchors: [
      { screen: 'workspaceLanding' },
    ],
  },
  {
    id: 'AQ6', theme: 'AQ', severity: 'p1', originalId: 'G6 + OB18', phase: 3,
    fieldTypes: ['longText', 'dropdown'],
    title: 'AI fields offer settings that create automations without enough detail and transparency',
    oneliner: 'Saving an AI field silently creates an automation that runs on every task creation event and consumes credits per run.',
    problem: "When a user saves an AI field, the Autofill automation toggle is ON by default. Saving creates an automation silently — Automations badge increments from 0 to 1; toast confirms creation. No copy explains the automation runs on every task creation event and consumes credits per run. The new-user manifestation is the 'Autofill when tasks are created' toggle pre-enabled silently on every new AI field.",
    fix: 'Default Autofill OFF for first AI field; add explicit pre-save disclosure of the automation and its cost.',
    variantsAffected: 'All AI templates · all entry points · new and power users',
    linkedFindings: ['AQ5', 'AQ9'],
    umbrella: 'CC1',
    evidenceTemplate: 'D',
    evidenceHeadline: 'Saving an AI field / creates an automation / silently.',
    userLens: ['New user', 'Power user', 'Admin'],
    goalAlignment: ['Adoption', 'CSAT'],
    anchors: [
      { screen: 'settings-longText', el: 'automations', anchor: 'top-right', offsetX: -6, offsetY: 6 },
      { screen: 'settings-dropdown', el: 'automations', anchor: 'top-right', offsetX: -6, offsetY: 6 },
    ],
  },
  {
    id: 'AQ7', theme: 'AQ', severity: 'p0', originalId: 'G7', phase: 1,
    fieldTypes: ['longText', 'dropdown'],
    title: 'The prompt variable picker has UX issues that cause friction and make the AI output unreliable',
    oneliner: 'Cursor drops after insertion. Accepts invalid fields. Output doesn\'t match the prompt — labels altered, fields reordered.',
    problem: 'The prompt variable picker (used to insert task properties like Title, Description, Comments into the prompt) has multiple UX issues: variables fail to insert as proper variables and instead get inserted as plain text, the picker doesn\'t clearly indicate what each variable returns, and inserted variables don\'t visually differentiate from surrounding prompt text. Result: users build prompts that don\'t substitute correctly at runtime — AI output is unreliable.',
    fix: 'Fix variable insertion reliability; render variables as visually distinct tokens.',
    variantsAffected: 'All AI templates · prompt variable picker · all entry points',
    linkedFindings: [],
    umbrella: 'CC1',
    evidenceTemplate: 'E',
    evidenceHeadline: 'Variable picker / causes friction, / unreliable output.',
    userLens: ['Power user'],
    goalAlignment: ['CSAT'],
    behavioral: true,
    anchors: [
      { screen: 'settings-longText', el: 'prompt', anchor: 'bottom-left', offsetX: 6, offsetY: -8 },
      { screen: 'settings-dropdown', el: 'prompt', anchor: 'bottom-left', offsetX: 6, offsetY: -8 },
    ],
  },
  {
    id: 'AQ8', theme: 'AQ', severity: 'p0', originalId: 'OB6', phase: 1,
    fieldTypes: ['longText', 'dropdown'],
    title: "Brain hits 'Rate limit reached for new account' on first interaction (intermittent)",
    oneliner: 'Brain auto-opens on first workspace landing. Next interaction returns rate-limit error in ~33% of audit passes.',
    problem: "On first workspace landing, Brain auto-opens in the right side panel with 'Welcome to ClickUp.' On at least one of three audit passes, the very next interaction returned the explicit error: 'Rate limit reached for new account, try again later.' Intermittent — other passes returned a normal personalized response.",
    fix: 'Suppress Brain auto-fire on first load; show a warm welcome state without triggering an API call.',
    variantsAffected: 'New accounts · workspace landing · ~33% of audited accounts',
    linkedFindings: [],
    evidenceTemplate: 'F',
    evidenceHeadline: 'Brain errors / on first try — / intermittent.',
    userLens: ['New user'],
    goalAlignment: ['Adoption'],
    anchors: [
      { screen: 'workspaceLanding' },
      { screen: 'brainHub' },
    ],
  },
  {
    id: 'AQ9', theme: 'AQ', severity: 'p2', originalId: 'OB19', phase: 3,
    fieldTypes: ['longText', 'dropdown'],
    title: 'No cost or credits warning visible during AI field configuration',
    oneliner: 'No per-run estimate, no monthly-quota indicator, no "this field will use X credits per task" forecast.',
    problem: "The Custom Field Settings panel for AI fields shows no per-run credit estimate, no monthly-quota indicator, no 'this field will use X credits per task' forecast. The user creates the field, the automation runs, credits consume — invisibly to the user during configuration.",
    fix: 'Add per-run estimate and quota usage to the Settings panel.',
    variantsAffected: 'All AI field configurations · all entry points',
    linkedFindings: ['AQ6', 'AQ5'],
    evidenceTemplate: 'A',
    evidenceHeadline: 'No cost or / credits warning / during config.',
    userLens: ['New user', 'Admin'],
    goalAlignment: ['CSAT'],
    anchors: [
      { screen: 'settings-longText', el: 'automations', anchor: 'top-right', offsetX: -6, offsetY: 38 },
      { screen: 'settings-dropdown', el: 'automations', anchor: 'top-right', offsetX: -6, offsetY: 38 },
    ],
  },
  {
    id: 'AQ10', theme: 'AQ', severity: 'p1', originalId: 'L5', phase: 1,
    fieldTypes: ['longText'],
    title: 'Default prompts bake in formatting instructions that conflict with Format dropdown',
    oneliner: 'Summary and Progress Updates prompts include "Use up to 4 lines." Action Items hardcodes "up to 4 action points."',
    problem: 'Default prompts for long text AI templates bake formatting instructions into the prompt text — even though there\'s a Format dropdown that should govern formatting. Summary and Progress Updates prompts include "Use up to 4 lines." Action Items prompt hardcodes "up to 4 action points." Format concerns mixed into the prompt instead of exposed as controls.',
    fix: 'Remove formatting instructions from default prompts; let Format dropdown govern structure.',
    variantsAffected: 'Summary · Progress Updates · Action Items templates',
    linkedFindings: ['AQ2'],
    evidenceTemplate: 'D',
    evidenceHeadline: 'Default prompts / bake in formatting / instructions.',
    userLens: ['Power user'],
    goalAlignment: ['CSAT'],
    behavioral: true,
    anchors: [
      { screen: 'settings-longText', el: 'prompt', anchor: 'bottom-left', offsetX: 6, offsetY: 28 },
    ],
  },
  {
    id: 'AQ11', theme: 'AQ', severity: 'p0', originalId: 'G25', phase: 3,
    fieldTypes: ['longText', 'dropdown'],
    title: 'AI field chains read stale upstream data — no refresh trigger',
    oneliner: 'AI fields can reference other AI fields. When upstream changes, downstream doesn\'t re-run. No manual refresh either.',
    problem: "AI fields can reference other custom fields (including other AI fields) as input. When upstream fields change, downstream AI fields don't automatically re-run — they read stale data. There's no manual refresh trigger either. Result: chained AI fields gradually diverge from upstream truth.",
    fix: 'Add cascading invalidation on upstream change + manual refresh trigger.',
    variantsAffected: 'All chained AI field configurations · both field types',
    linkedFindings: [],
    evidenceTemplate: 'B',
    evidenceHeadline: 'AI field chains / read stale / upstream data.',
    userLens: ['Power user', 'Admin'],
    goalAlignment: ['CSAT'],
    anchors: [
      { screen: 'settings-longText', el: 'prompt', anchor: 'bottom-right', offsetX: -6, offsetY: -34 },
      { screen: 'settings-dropdown', el: 'prompt', anchor: 'bottom-right', offsetX: -6, offsetY: -34 },
    ],
  },
  {
    id: 'AQ12', theme: 'AQ', severity: 'p1', originalId: 'D2', phase: 1,
    fieldTypes: ['dropdown'],
    title: 'Categorize and Custom Dropdown are the same simple template',
    oneliner: '4 dropdown templates, only 2 genuinely pre-configured. Categorize ships with Option 1/Option 2 just like Custom.',
    problem: "Categorize and Custom Dropdown templates are functionally identical — same generic Option 1/Option 2 defaults, near-identical 'choose the most appropriate option' prompts, same workflow required. The only difference is auto-populated Field name. Categorize looks like a curated template but is Custom Dropdown in disguise.",
    fix: "Remove Categorize; fix Custom Dropdown's empty state to guide users.",
    variantsAffected: 'Categorize template · Custom Dropdown template',
    linkedFindings: ['AD2'],
    evidenceTemplate: 'B',
    evidenceHeadline: 'Categorize and / Custom Dropdown: / same template.',
    userLens: ['New user', 'Power user'],
    goalAlignment: ['Adoption', 'CSAT'],
    anchors: [
      { screen: 'settings-dropdown', el: 'template', anchor: 'top-right', offsetX: -6, offsetY: 52 },
      { screen: 'typeSelection', el: 'all-fields', anchor: 'top-right', offsetX: -6, offsetY: 60 },
    ],
  },

  /* ============================================================
     AD — AI Discovery + Adoption (18)
  ============================================================ */
  {
    id: 'AD1', theme: 'AD', severity: 'p1', originalId: 'G24', phase: 2,
    fieldTypes: ['longText', 'dropdown'],
    title: 'Template dropdown lacks descriptions, sample outputs, or previews',
    oneliner: 'Template dropdown shows only template names. No description, no sample, no preview. New users have to guess.',
    problem: 'The Template dropdown (Sentiment / T-shirt Size / Categorize / Custom Dropdown / Summary / Progress Updates / Translation / Action Items / Custom Instructions) shows only template names. No description, no sample output, no preview. New users picking a template have to guess what each does.',
    fix: 'Add description + sample output preview to each template option.',
    variantsAffected: 'All AI templates · all field types · all entry points',
    linkedFindings: [],
    evidenceTemplate: 'D',
    evidenceHeadline: 'Template dropdown: / bare names, / no descriptions.',
    userLens: ['New user', 'Power user'],
    goalAlignment: ['Adoption', 'CSAT'],
    anchors: [
      { screen: 'settings-longText', el: 'template', anchor: 'top-right', offsetX: -6, offsetY: 34 },
      { screen: 'settings-dropdown', el: 'template', anchor: 'top-right', offsetX: -6, offsetY: 34 },
    ],
  },
  {
    id: 'AD2', theme: 'AD', severity: 'p0', originalId: 'T2', phase: 1,
    fieldTypes: ['longText', 'dropdown'],
    title: 'Duplicate field entries in the picker',
    oneliner: 'Custom Text / Summary / Categorize / Custom Dropdown appear in both "AI fields" and "All." Tasks and Relationship are the same field under two names.',
    problem: "Two duplication patterns in all three picker variants: (1) AI variants (Custom Text, Summary, Custom Dropdown, Categorize) duplicated across 'AI fields' and 'All' sections, sometimes under different names; (2) Tasks and Relationship are the same field type but appear as separate entries.",
    fix: 'Show each data type once; use Brain icon on AI-capable rows; dedup Tasks/Relationship.',
    variantsAffected: 'All three picker variants · all entry points',
    linkedFindings: ['CS12', 'AQ12'],
    evidenceTemplate: 'A',
    evidenceHeadline: 'Duplicate field / entries in / the picker.',
    userLens: ['New user', 'Power user'],
    goalAlignment: ['Adoption', 'CSAT'],
    anchors: [
      { screen: 'typeSelection', el: 'ai-fields', anchor: 'top-right', offsetX: -6, offsetY: 6 },
    ],
  },
  {
    id: 'AD3', theme: 'AD', severity: 'p1', originalId: 'G9', phase: 1,
    fieldTypes: ['longText', 'dropdown'],
    title: "ClickUp Brain isn't consistently branded across any AI-related screen",
    oneliner: 'Brain has four names across the product: "Brain," "ClickUp AI," "AI," "Tell AI." Same product, multiple names.',
    problem: "Brain is referred to by at least four names across the product: 'Brain' (Brain hub, right panel), 'ClickUp AI' (Planner page), 'AI' (sidebar icon, wizard Step 6), 'Tell AI' (form copy). Same product, multiple names. No visual consistency either — the Brain icon shows in some places, not others.",
    fix: 'Standardize on "Brain" everywhere; retire "ClickUp AI" alias.',
    variantsAffected: 'Wizard Step 6 · Planner · AI field config · Brain hub · Sidebar nav · Get Started AI task',
    linkedFindings: ['AD10', 'AD8'],
    evidenceTemplate: 'C',
    evidenceHeadline: 'Brain has / four names / across the product.',
    userLens: ['New user', 'Power user'],
    goalAlignment: ['Adoption', 'CSAT'],
    anchors: [
      { screen: 'settings-longText', el: 'prompt', anchor: 'top-left', offsetX: 6, offsetY: 6 },
      { screen: 'settings-dropdown', el: 'prompt', anchor: 'top-left', offsetX: 6, offsetY: 6 },
      { screen: 'plannerPage' },
      { screen: 'sidebarNav' },
      { screen: 'brainHub' },
    ],
  },
  {
    id: 'AD4', theme: 'AD', severity: 'p2', originalId: 'T10', phase: 1,
    fieldTypes: ['longText', 'dropdown'],
    title: "Field type tooltips need a full copy pass — including Brain icon + 'AI:' lead-in for AI-capable rows",
    oneliner: '~33 tooltips with voice inconsistencies, factual errors, and no AI signal on AI-capable rows.',
    problem: "All ~33 field type tooltips in the picker have copy issues: voice inconsistencies (imperative, declarative, marketing-speak running in parallel), filler ('important,' 'any,' 'even' appear 20+ times), AI tooltip duplicates, factually wrong tooltips (Sentiment doesn't say it picks an option; T-shirt Size is a sentence fragment; Categorize and Custom Dropdown have identical copy). Plus AI-capable rows (Long Text, Dropdown) need a Brain icon + 'AI:' lead-in to signal AI capability.",
    fix: "Run the full tooltip copy pass; add Brain icon + 'AI:' lead-in on AI-capable rows.",
    variantsAffected: 'All three picker variants · all 33 field types · AI-capable rows specifically',
    linkedFindings: ['AD2'],
    evidenceTemplate: 'D',
    evidenceHeadline: '33 tooltips, / three voices, / no AI signal.',
    userLens: ['New user', 'Power user'],
    goalAlignment: ['Adoption', 'CSAT'],
    anchors: [
      { screen: 'typeSelection', el: 'all-fields', anchor: 'top-left', offsetX: 6, offsetY: 100 },
    ],
  },
  {
    id: 'AD5', theme: 'AD', severity: 'p2', originalId: 'OB2', phase: 1.5,
    fieldTypes: ['longText', 'dropdown'],
    title: "Onboarding - Wizard Step 5 ('Do you use any of these tools?') — Competitor signal (Notion, Monday) collected but no personalization downstream",
    oneliner: "Step 5 asks about Notion and Monday. Selection is collected. Post-signup experience shows no personalization.",
    problem: "Wizard Step 5 asks 'Do you use any of these tools?' and lists Notion and Monday as options — both ClickUp's closest AI-feature competitors. The selection is collected. Post-signup experience shows no visible personalization — a user who flagged Notion AI gets the same workspace and Get Started tasks as a user who flagged Trello.",
    fix: 'Route Notion/Monday/Asana selectors to AI-content first; or render a Brain-vs-competitor comparison.',
    variantsAffected: 'Users selecting Notion / Monday / Asana on Step 5',
    linkedFindings: ['AD6'],
    evidenceTemplate: 'A',
    evidenceHeadline: 'Step 5 captures / competitor signal, / uses none of it.',
    userLens: ['New user'],
    goalAlignment: ['Adoption'],
    anchors: [{ screen: 'wizardStep5' }],
  },
  {
    id: 'AD6', theme: 'AD', severity: 'p2', originalId: 'OB3', phase: 1.5,
    fieldTypes: ['longText', 'dropdown'],
    title: "Onboarding - Wizard Step 5 ('Do you use any of these tools?') — AI tools omitted from selections (inconsistent with Step 3)",
    oneliner: "Step 3 includes 'AI Tools' as attribution. Step 5's tool-stack list omits AI tools entirely.",
    problem: "Step 3 ('How did you hear about us?') includes 'AI Tools (ChatGPT, Perplexity, etc.)' as an attribution source. Step 5's tool-stack list omits AI tools entirely (no ChatGPT, Claude, Gemini, Notion AI, Copilot). The wizard treats AI as a referral source but not as a tool the user might already be paying for.",
    fix: 'Add AI tools row to Step 5; use the signal to position Brain.',
    variantsAffected: 'All new user signups · Wizard Step 5',
    linkedFindings: ['AD5'],
    evidenceTemplate: 'B',
    evidenceHeadline: 'Step 5 omits / AI tools from / the stack list.',
    userLens: ['New user'],
    goalAlignment: ['Adoption'],
    anchors: [{ screen: 'wizardStep5' }],
  },
  {
    id: 'AD7', theme: 'AD', severity: 'p0', originalId: 'OB5', phase: 1.5,
    fieldTypes: ['longText', 'dropdown'],
    title: 'Onboarding - New Workspace landing — Brain personalizes from PMO signal but never mentions AI Custom Fields',
    oneliner: "Brain's first-run prompts reference PMO selection. None mention AI Custom Fields by name.",
    problem: "On first workspace landing, Brain auto-opens with personalized welcome explicitly referencing PMO selection from the wizard. Two follow-up prompt suggestions are offered, including 'Create a PMO solution called \"PMO Command Center\" with AI-powered weekly summaries.' Neither prompt mentions AI Custom Fields specifically — even though 'AI-powered weekly summaries' is functionally an AI Custom Fields use case.",
    fix: "Add AI Custom Fields prompts to Brain's first-run follow-ups; scope to the user's selected function.",
    variantsAffected: 'All new user accounts · workspace landing',
    linkedFindings: [],
    evidenceTemplate: 'A',
    evidenceHeadline: 'Brain personalizes / from PMO, / skips AI fields.',
    userLens: ['New user'],
    goalAlignment: ['Adoption'],
    anchors: [
      { screen: 'workspaceLanding' },
      { screen: 'brainHub' },
    ],
  },
  {
    id: 'AD8', theme: 'AD', severity: 'p1', originalId: 'OB7', phase: 1,
    fieldTypes: ['longText', 'dropdown'],
    title: 'Onboarding - Sidebar exploration — AI sidebar and right Brain panel are mutually exclusive surfaces with no explanation',
    oneliner: 'Sidebar AI icon opens full-page Brain hub. Right Brain panel disappears. No explanation they\'re the same product.',
    problem: "The left sidebar's 'AI' icon opens a full-page Brain hub at /ai/brain. The right-side Brain panel disappears when this page is active. Two AI surfaces, functionally distinct (full-page hub vs side panel chat), but a new user has no way to know which one to use, or that they're the same product.",
    fix: "Consolidate or add an explainer; clarify they're the same Brain.",
    variantsAffected: 'All new users · sidebar AI icon · right Brain panel',
    linkedFindings: ['AD3'],
    evidenceTemplate: 'B',
    evidenceHeadline: 'Two Brain surfaces, / mutually exclusive, / never explained.',
    userLens: ['New user'],
    goalAlignment: ['Adoption'],
    anchors: [
      { screen: 'sidebarNav' },
      { screen: 'brainHub' },
    ],
  },
  {
    id: 'AD9', theme: 'AD', severity: 'p1', originalId: 'OB8', phase: 1.5,
    fieldTypes: ['longText', 'dropdown'],
    title: 'Onboarding - Sidebar exploration — 5 distinct page treatments, none introduce AI',
    oneliner: 'Five sidebar pages, each with different empty-state treatments. None introduce AI Custom Fields.',
    problem: 'Each main sidebar icon (Home, Planner, AI, Teams, More) lands on a different page with different empty-state treatments. None of them introduce AI Custom Fields. Five chances to introduce the feature; zero taken.',
    fix: 'Add AI Custom Fields tile to Brain hub; coach mark on Home empty state.',
    variantsAffected: 'All new user navigation · Home / Planner / AI / Teams / More',
    linkedFindings: [],
    evidenceTemplate: 'C',
    evidenceHeadline: 'Five sidebar pages, / zero introduce / AI Custom Fields.',
    userLens: ['New user'],
    goalAlignment: ['Adoption'],
    anchors: [{ screen: 'sidebarNav' }],
  },
  {
    id: 'AD10', theme: 'AD', severity: 'p1', originalId: 'OB9', phase: 1,
    fieldTypes: ['longText', 'dropdown'],
    title: "Onboarding - First Planner page interaction — Brain branded as 'ClickUp AI' (inconsistent with Brain hub)",
    oneliner: "Planner says 'powered by ClickUp AI.' Brain hub uses 'Brain.' Same product, two names, on adjacent pages.",
    problem: "The Planner page (/calendar) shows: 'Connect your calendar to manage events, time block your work, and take meeting notes — powered by ClickUp AI.' The Brain hub at /ai/brain and the right side panel both use 'Brain' branding. Same product, two names, on adjacent pages.",
    fix: "Standardize on 'Brain'; retire 'ClickUp AI' on Planner page.",
    variantsAffected: 'Planner page · Get Started AI task body · form copy',
    linkedFindings: ['AD3'],
    evidenceTemplate: 'B',
    evidenceHeadline: "Planner says / 'ClickUp AI'. / Brain hub says 'Brain'.",
    userLens: ['New user'],
    goalAlignment: ['Adoption'],
    anchors: [{ screen: 'plannerPage' }],
  },
  {
    id: 'AD11', theme: 'AD', severity: 'p0', originalId: 'OB10', phase: 5,
    fieldTypes: ['longText', 'dropdown'],
    title: 'Onboarding - First Brain hub interaction — Brain answers in free-form chat instead of structured discovery cards (Brain-as-trainer gap)',
    oneliner: "'Explore more AI features' banner submits prompt. Brain returns free-form prose after 20+ seconds, missing AI Custom Fields.",
    problem: "The Brain hub carries a banner: 'Explore more AI features — Autopilot Agents, Meeting Notetaker, AI fields and more.' Clicking it auto-submits the prompt 'Recommend ClickUp AI Features based on my activity' to Brain. Brain shows 'Thinking — Analyzing — Search activity' for 20+ seconds, then returns free-form prose. For a brand-new account with no activity, the prompt has no useful basis to answer from. AI Custom Fields not in the eventual response.",
    fix: "Build Brain's onboarding-trainer response mode; structured feature cards with 'Try it' deep links.",
    variantsAffected: 'All new users · Brain hub feature-discovery banner',
    linkedFindings: ['AD17'],
    evidenceTemplate: 'F',
    evidenceHeadline: 'Brain answers / in chat, not / in structured cards.',
    userLens: ['New user'],
    goalAlignment: ['Adoption'],
    anchors: [{ screen: 'brainHub' }],
  },
  {
    id: 'AD12', theme: 'AD', severity: 'p1', originalId: 'OB11', phase: 1.5,
    fieldTypes: ['longText', 'dropdown'],
    title: "Onboarding - First Brain hub interaction — Quick-prompt cards don't introduce AI Custom Fields",
    oneliner: "Brain hub has four sample-prompt cards. None mention AI Custom Fields.",
    problem: 'The Brain hub presents four sample-prompt cards: Brainstorm Ideas / Create Task / Summarize Task / Improve Writing. All four are oriented at writing or task creation. None introduce AI Custom Fields.',
    fix: "Add a 5th tile: 'Set up an AI field' — deep links to picker with AI section pre-expanded.",
    variantsAffected: 'All users on the Brain hub',
    linkedFindings: [],
    evidenceTemplate: 'A',
    evidenceHeadline: 'Brain hub cards / miss AI / Custom Fields.',
    userLens: ['New user'],
    goalAlignment: ['Adoption'],
    anchors: [{ screen: 'brainHub' }],
  },
  {
    id: 'AD13', theme: 'AD', severity: 'p1', originalId: 'OB12', phase: 1.5,
    fieldTypes: ['longText', 'dropdown'],
    title: 'Onboarding - Get Started list — AI task positioned last with latest due date',
    oneliner: 'AI task is 6th of 6 in Get Started list. Due Friday vs Tomorrow / Tue / Wed / Thu for earlier tasks.',
    problem: "The 'Get Started with ClickUp' list contains 6 onboarding tasks. The AI task ('🍰 Work Smarter with ClickUp AI') is the 6th and final task, due Friday (vs Tomorrow / Tue / Wed / Thu for earlier tasks). Users who don't complete the full sequence (most users) never reach the AI task.",
    fix: 'Move AI task to position 1 or 2; due date Today.',
    variantsAffected: 'All new users following the Get Started sequence',
    linkedFindings: [],
    evidenceTemplate: 'A',
    evidenceHeadline: 'AI task is last / in the / Get Started list.',
    userLens: ['New user'],
    goalAlignment: ['Adoption'],
    anchors: [{ screen: 'getStartedList' }],
  },
  {
    id: 'AD14', theme: 'AD', severity: 'p0', originalId: 'OB13', phase: 1.5,
    fieldTypes: ['longText', 'dropdown'],
    title: 'Onboarding - Get Started AI task — Markets 4 use cases, none are AI Custom Fields',
    oneliner: '"Work Smarter with ClickUp AI" markets four use cases. AI Custom Fields appears only as a sample question.',
    problem: "The 'Work Smarter with ClickUp AI' task body markets ClickUp AI as 'your intelligent co-pilot, seamlessly integrated into your workspace to help you write, summarize, brainstorm, get instant answers, and even take meeting notes.' Four use cases: write, summarize, brainstorm, meeting notes. The only mention of 'Custom Field' is as a sample question to ask Brain — not as a feature to try.",
    fix: "Add 5th section: 'Autofill structured fields with AI' + 'Try it' deep link.",
    variantsAffected: 'All new users who reach Get Started task #6',
    linkedFindings: [],
    evidenceTemplate: 'A',
    evidenceHeadline: 'AI task markets / four use cases, / no AI fields.',
    userLens: ['New user'],
    goalAlignment: ['Adoption'],
    anchors: [{ screen: 'getStartedAITask' }],
  },
  {
    id: 'AD15', theme: 'AD', severity: 'p0', originalId: 'OB14', phase: 1.5,
    fieldTypes: ['longText', 'dropdown'],
    title: 'Onboarding - Get Started workflow task — Custom Fields mentioned once, no AI variant',
    oneliner: 'Get Started task #2 teaches a manual Text Custom Field. AI is not mentioned.',
    problem: "Get Started task #2 ('🐢 Design a Workflow That Works for You') contains a checklist item: 'Add a Custom Field — Track the details that matter most with Custom Fields. For this task, scroll down to the \"Add fields\" button and click the \"+\" icon. Add a \"Text\" Custom Field named \"Project Lead\" and enter your name.' Followed by a link: '👉 All about Custom Fields' (URL: help.clickup.com/...). The instructions teach a manual Text Custom Field. AI is not mentioned.",
    fix: 'Rewrite checklist item to teach AI Custom Field; demote manual to fallback.',
    variantsAffected: 'All new users who reach Get Started task #2',
    linkedFindings: [],
    evidenceTemplate: 'A',
    evidenceHeadline: 'Custom Fields / mentioned once, / no AI variant.',
    userLens: ['New user'],
    goalAlignment: ['Adoption'],
    anchors: [{ screen: 'getStartedWorkflowTask' }],
  },
  {
    id: 'AD16', theme: 'AD', severity: 'p0', originalId: 'OB15', phase: 1.5,
    fieldTypes: ['longText', 'dropdown'],
    title: 'Onboarding - Discovery path — AI Custom Fields documentation is 5 clicks deep',
    oneliner: 'Discovery path is five clicks. Three of them leave ClickUp.',
    problem: "Full discovery path for AI Custom Fields, as it exists today: (1) Open Get Started list; (2) Open task #2 'Design a Workflow That Works for You'; (3) Click 'All about Custom Fields' link → leaves ClickUp, opens help.clickup.com; (4) Read Custom Fields help article; (5) Find and click link to separate 'AI Fields' sub-article. Three of those five clicks are external to ClickUp. None of the in-product copy uses the phrase 'AI Custom Fields.'",
    fix: 'Add in-product entry points (Brain hub tile, Get Started section, Home coach mark) to close the gap.',
    variantsAffected: 'All new users',
    linkedFindings: [],
    evidenceTemplate: 'E',
    evidenceHeadline: 'AI Custom Fields / documentation is / 5 clicks deep.',
    userLens: ['New user'],
    goalAlignment: ['Adoption'],
    anchors: [{ screen: 'helpDocs' }],
  },
  {
    id: 'AD17', theme: 'AD', severity: 'p0', originalId: 'OB24', phase: 5,
    fieldTypes: ['longText', 'dropdown'],
    title: 'Onboarding - Global search — Workspace search for AI Custom Fields returns no help-doc results',
    oneliner: "Cmd+K search for 'ai custom field' returns one task. No help docs.",
    problem: "Searching the global search bar (Cmd+K) for 'ai custom field' returns exactly one result: the existing 'Work Smarter with ClickUp AI' task. Help articles live at help.clickup.com and aren't indexed in workspace search. New users typing a help-pattern query into workspace search expect an answer, get one task, and assume ClickUp has nothing to say about AI Custom Fields.",
    fix: 'Add Help docs filter to global search; route help-pattern queries through Brain.',
    variantsAffected: 'All new users searching for AI feature names · all help-pattern queries',
    linkedFindings: ['AD11'],
    evidenceTemplate: 'A',
    evidenceHeadline: 'Workspace search / for AI fields / returns no help docs.',
    userLens: ['New user'],
    goalAlignment: ['Adoption'],
    anchors: [{ screen: 'globalSearch' }],
  },
  {
    id: 'AD18', theme: 'AD', severity: 'p0', originalId: 'OB25', phase: 1.5,
    fieldTypes: ['longText', 'dropdown'],
    title: "Onboarding - New Workspace landing — Workspace setup is opaque (Brain knows the user's role but doesn't show it)",
    oneliner: 'New user lands in a workspace with two pre-created Spaces. No explanation of what was created or why.',
    problem: "After onboarding, the new user is dropped into a workspace with two pre-created Spaces and a structure they didn't choose. There's no explanation of what was created, why these specific Spaces, or what to do with them. Brain knows the user's role from wizard Step 4 — it could say 'I set up your space with X because you're a Y' — and instead the workspace lands cold.",
    fix: "Add 'Setting up your workspace…' interstitial that explains setup using onboarding signal.",
    variantsAffected: 'All new users · workspace landing · all PMO/role variants',
    linkedFindings: [],
    evidenceTemplate: 'A',
    evidenceHeadline: 'Workspace setup / is opaque — / Brain stays silent.',
    userLens: ['New user'],
    goalAlignment: ['Adoption'],
    anchors: [{ screen: 'workspaceLanding' }],
  },

  /* ============================================================
     FG — Feature Gaps (4)
  ============================================================ */
  {
    id: 'FG1', theme: 'FG', severity: 'p0', originalId: 'G8', phase: 2,
    fieldTypes: ['longText', 'dropdown'],
    title: "There's no way to preview the prompt or test-run it before saving",
    oneliner: 'Users commit a prompt blind. Bad prompt = bad fills before they realize.',
    problem: "AI field configuration has no way to preview the prompt's output or test-run before saving. User writes a prompt, configures variables, saves the field — and only then sees the AI's actual output. If the prompt produces nonsense, the user has to delete and reconfigure.",
    fix: 'Add Preview / Test-run that shows sample AI output before saving.',
    variantsAffected: 'All AI templates · all entry points · both field types',
    linkedFindings: ['AQ2', 'AQ6'],
    evidenceTemplate: 'B',
    evidenceHeadline: 'No preview / before saving / an AI field.',
    userLens: ['New user', 'Power user'],
    goalAlignment: ['Adoption', 'CSAT'],
    anchors: [
      { screen: 'settings-longText', el: 'prompt', anchor: 'bottom-right', offsetX: -6, offsetY: -8 },
      { screen: 'settings-dropdown', el: 'prompt', anchor: 'bottom-right', offsetX: -6, offsetY: -8 },
    ],
  },
  {
    id: 'FG2', theme: 'FG', severity: 'p0', originalId: 'OB21', phase: 3,
    fieldTypes: ['longText', 'dropdown'],
    title: 'Custom Field Manager displays AI fields as visually identical to manual field counterparts',
    oneliner: 'CFM shows AI fields as visually identical to manual Text fields. No Brain icon, no AI badge, no template column.',
    problem: "After creating an AI field, opening Custom Field Manager shows the field grouped under 'Text area (Long Text)' with a generic text icon. No Brain icon. No AI badge. No template column. No prompt preview. No last-run timestamp. No error/health indicator. CFM displays an AI field as visually identical to a manual Text field.",
    fix: "Add AI Status column to CFM with Brain icon, template, last-run, error rate, and 'AI only' filter.",
    variantsAffected: 'All workspaces with AI fields · CFM entry point',
    linkedFindings: [],
    evidenceTemplate: 'B',
    evidenceHeadline: 'CFM hides / the AI nature / of fields.',
    userLens: ['Admin', 'New user', 'Power user'],
    goalAlignment: ['CSAT'],
    anchors: [
      { screen: 'cfm', el: '__panel__' },
    ],
  },
  {
    id: 'FG3', theme: 'FG', severity: 'p1', originalId: 'G26', phase: 5,
    fieldTypes: ['longText', 'dropdown'],
    title: 'AI field output is text-only',
    oneliner: 'AI fields can only return text. No image, file, link, rich-text, or structured-data output.',
    problem: 'AI fields can only return text output. No image, file, link, rich-text, or structured-data output type. Limits the use cases AI fields can serve.',
    fix: 'Expand AI output types: image, file, link, rich-text, structured data.',
    variantsAffected: 'All AI templates · output type system-wide',
    linkedFindings: [],
    evidenceTemplate: 'C',
    evidenceHeadline: 'AI field output / is text-only.',
    userLens: ['Power user'],
    goalAlignment: ['CSAT'],
    anchors: [
      { screen: 'settings-longText', el: 'template', anchor: 'bottom-left', offsetX: 6, offsetY: 60 },
      { screen: 'settings-dropdown', el: 'template', anchor: 'bottom-left', offsetX: 6, offsetY: 60 },
    ],
  },
  {
    id: 'FG4', theme: 'FG', severity: 'p1', originalId: 'G27', phase: 2,
    fieldTypes: ['longText', 'dropdown'],
    title: 'No prompt or template library — every AI field reconfigures from scratch',
    oneliner: 'Power users rewrite the same prompts repeatedly. Admins can\'t standardize prompts across teams.',
    problem: 'No way to save a prompt for reuse across fields. The dropdown template library is also underbuilt (4 entries, only 2 genuinely curated). Every AI field is configured from scratch — power users rewrite the same prompts repeatedly; admins can\'t standardize prompts across teams. The product lacks both per-user (saved prompts) and product-level (template expansion) library infrastructure.',
    fix: 'Build Saved Prompts (Phase 2) + expand template library (Phase 4A).',
    variantsAffected: 'Long Text · Dropdown · all AI templates · all users',
    linkedFindings: ['AQ12', 'AD1'],
    evidenceTemplate: 'C',
    evidenceHeadline: 'No prompt library. / Every AI field / starts from scratch.',
    userLens: ['Power user', 'Admin'],
    goalAlignment: ['CSAT'],
    anchors: [
      { screen: 'settings-longText', el: 'template', anchor: 'bottom-left', offsetX: 6, offsetY: 84 },
      { screen: 'settings-dropdown', el: 'template', anchor: 'bottom-left', offsetX: 6, offsetY: 84 },
    ],
  },
];

/* ============================================================================
   L1 — 13 Design Moves (Type Selection: 5 + Settings: 8)
   ============================================================================
   Per drafts/L1_design_moves.md (locked 2026-04-30).
   L1 anchors are MOVES, not findings. Each move resolves N findings.
   Rail card pulls: { what, why, resolves: [findingIds] }
============================================================================ */

const DESIGN_MOVES = [
  /* -------------------- Type Selection — 5 moves -------------------- */
  {
    id: 'TS-1',
    surface: 'typeSelection',
    title: 'Width unification',
    what: 'Task adopts View\'s full panel width (was 308px, now matches View at 380px).',
    why: 'The narrower Task variant cropped Suggested + had less room for hierarchy. Unifying width = unifying capability.',
    resolves: ['CS6'],
    anchorProposed: { el: 'header', anchor: 'top-left', offsetX: 10, offsetY: 6 },
  },
  {
    id: 'TS-2',
    surface: 'typeSelection',
    title: 'Functional grouping replaces flat scroll',
    what: '~33 field types organized into 6 functional groups (Text · Selection · Numbers & Dates · Links & Attachments · Relationships · Actions & Tracking). Old "AI vs standard" split removed.',
    why: 'Architecture-driven grouping (AI vs standard) reflects code, not user intent. New user scanning for "priority" needs intent-driven groups.',
    resolves: ['CS9'],
    anchorProposed: { el: 'group-text', anchor: 'top-right', offsetX: -6, offsetY: 6 },
  },
  {
    id: 'TS-3',
    surface: 'typeSelection',
    title: 'Suggested section adopted in Task',
    what: 'Task entry gets a Suggested section using View\'s logic, enriched with task-level signals.',
    why: 'Task has richer context than View (List, Space, task title, description, assignees, comments). Capability leak — fix is to render Suggested everywhere with appropriate signal source.',
    resolves: ['CS8'],
    anchorProposed: { el: 'suggested', anchor: 'top-right', offsetX: -6, offsetY: 6 },
  },
  {
    id: 'TS-4',
    surface: 'typeSelection',
    title: 'Inline tabs replace pre-step popup',
    what: '"Create new" / "Add existing" tabs inside the picker. The Task pre-step popup ("Create / Add from Workspace") is killed.',
    why: 'No way to switch modes inside picker today — pick wrong, back out, restart. Inline tabs put both options at the same level.',
    resolves: ['CS10'],
    anchorProposed: { el: 'header', anchor: 'top-left', offsetX: 10, offsetY: 50 },
  },
  {
    id: 'TS-5',
    surface: 'typeSelection',
    title: 'Field deduplication + canonical naming',
    what: 'One entry per field type (no duplicates). Canonical names match catalog, picker rows, preview cards, and config panels.',
    why: 'Duplicates make the list look broken on first scan; cross-surface naming mismatches break trust.',
    resolves: ['AD2', 'CS12'],
    anchorProposed: { el: 'all-fields', anchor: 'top-right', offsetX: -6, offsetY: 6 },
  },

  /* -------------------- Settings Screen — 8 moves -------------------- */
  {
    id: 'SS-1',
    surface: 'settings',
    title: 'Form coordinates as one unit (Template cascade)',
    what: 'Template change cascades to dependent controls (Field name, Format, Property, Language, dropdown options) — each resets to the new template\'s default. User edits preserved.',
    why: 'Header type picker handles cascade correctly; Template doesn\'t. Fields end up mis-labeled, with stale options, with stuck Format/Property pickers. Treating the panel as a coordinated form with one source of truth (Template) and one cascade rule (reset unless edited) fixes all of it.',
    resolves: ['CC1', 'CC2', 'CC3', 'CC4', 'CC5'],
    anchorProposed: { el: 'template', anchor: 'top-right', offsetX: -6, offsetY: 6 },
  },
  {
    id: 'SS-2',
    surface: 'settings',
    title: 'Fill method switcher always visible',
    what: 'Manual / Fill with AI switcher renders on every entry path — manual→AI AND AI-direct.',
    why: 'Path was carrying state the form didn\'t acknowledge. Two users on what they think is the same template pulled from different defaults.',
    resolves: ['CS14'],
    anchorProposed: { el: 'fill-method-missing', anchor: 'top-right', offsetX: -6, offsetY: 6 },
  },
  {
    id: 'SS-3',
    surface: 'settings',
    title: 'Default unification across paths',
    what: 'All template-driven defaults unify across paths. Progress Updates defaults to "Last 24 hours" everywhere (was "Today" on manual→AI path). Field name pre-population follows one rule.',
    why: 'Two users configuring the same template should get the same field. Brain output should not depend on which screen the user came from.',
    resolves: ['CS16'],
    anchorProposed: { el: 'template', anchor: 'bottom-right', offsetX: -6, offsetY: -6 },
  },
  {
    id: 'SS-4',
    surface: 'settings',
    title: 'Permissions become field-level',
    what: 'Permissions controls (visibility, role-restrict) move out of "View entry only" into the More Settings section on every variant.',
    why: 'Workspace admins using CFM had fewer controls than team members creating a field inline. Permissions are a field property, not a View-only capability.',
    resolves: ['CS15'],
    anchorProposed: { el: 'more', anchor: 'top-right', offsetX: -6, offsetY: 4 },
  },
  {
    id: 'SS-5',
    surface: 'settings',
    title: 'Description placement consistent',
    what: 'Description field appears in the same position across all three entry-point variants (View / Task / CFM).',
    why: 'Description was buried in More Settings on View, on top with helper copy on Task, missing on CFM. Same field, three placements.',
    resolves: ['CS2'],
    anchorProposed: { el: 'more', anchor: 'top-right', offsetX: -6, offsetY: 36 },
  },
  {
    id: 'SS-6',
    surface: 'settings',
    title: 'Eight micro-inconsistencies unified',
    what: '"Visible to Guests" casing, "Pinned" toggle, prompt textarea size, and five other controls share one resolution rule across variants.',
    why: 'Small inconsistencies compound. One pattern (cluster) needs one resolution.',
    resolves: ['CS4', 'CS3'],
    anchorProposed: { el: 'more', anchor: 'top-left', offsetX: 6, offsetY: 4 },
  },
  {
    id: 'SS-7',
    surface: 'settings',
    title: 'Prompt variable picker gets a real picker UI',
    what: 'The prompt\'s variable insertion gets a proper picker affordance with previews + clear feedback on selection.',
    why: 'Current variable picker has UX issues that cause friction; AI output unreliable when users can\'t trust the variable insertion.',
    resolves: ['AQ7'],
    anchorProposed: { el: 'prompt', anchor: 'bottom-left', offsetX: 6, offsetY: -8 },
  },
  {
    id: 'SS-8',
    surface: 'settings',
    title: 'Trigger copy + tooltips cleaned up',
    what: 'Automation trigger label changes from "Auto update when tasks change" to "Auto update when task is updated" (matches Automations screen). Redundant "Tell AI how to fill" tooltip dropped.',
    why: 'Trigger copy mismatched the actual Automation that fires. Redundant tooltip duplicates label info.',
    resolves: ['CS13', 'AQ1'],
    anchorProposed: { el: 'autom-trigger', anchor: 'top-right', offsetX: -6, offsetY: 2 },
  },
];

/* ============================================================================
   Helpers
============================================================================ */

// Find a finding by ID.
function findingById(id) {
  return FINDINGS.find(f => f.id === id);
}

// Find an umbrella by ID.
function umbrellaById(id) {
  return UMBRELLAS.find(u => u.id === id);
}

// Find a design move by ID.
function moveById(id) {
  return DESIGN_MOVES.find(m => m.id === id);
}

// Findings whose anchors[] include the given screen.
function findingsForScreen(screen) {
  return FINDINGS.filter(f => f.anchors.some(a => a.screen === screen));
}

// Findings filtered by theme code (CC | CS | AQ | AD | FG) or 'all'.
function findingsByTheme(theme) {
  if (theme === 'all' || !theme) return FINDINGS;
  return FINDINGS.filter(f => f.theme === theme);
}

// Resolve linked findings — accepts array of IDs OR a comma-separated string.
function resolveLinks(linksArr) {
  if (!Array.isArray(linksArr)) return [];
  return linksArr.map(id => findingById(id)).filter(Boolean);
}

/* ============================================================================
   Exports — exposed on window for vanilla-JS prototypes (no module bundler)
============================================================================ */

if (typeof window !== 'undefined') {
  window.CATALOG = {
    THEMES,
    SEVERITY,
    SCREENS,
    ONBOARDING_STAGES,
    UMBRELLAS,
    FINDINGS,
    DESIGN_MOVES,
    findingById,
    umbrellaById,
    moveById,
    findingsForScreen,
    findingsByTheme,
    resolveLinks,
  };
}
